import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Header from '@/pages/components/Header';
import Footer from '@/pages/components/Footer';
import Breadcrumbs from '@/pages/components/Breadcrumbs';
import Sidebar from '@/pages/components/Sidebar';

function PostDetail() {
  const router = useRouter()
  const { postSlug } = router.query

  const [postData, setPostData] = useState(null);
  useEffect(() => {
      async function fetchData() {
      const response = await fetch(`http://127.0.0.1:8000/api/v1/posts/${postSlug}`);
      const data = await response.json();
      setPostData(data);
      }
      fetchData();
  }, [postSlug]);

if (!postData) {
  return <div>Loading...</div>;
}

const crumbs = [
  { name: 'главная', path: '/' },
  { name: 'категории', path: '/categories' },
  { name: postData.title, path: null },
];

console.log(postData);
  return (
    <>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
          <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='post-detail'>
          <Header/>
          <div className='container'>
            <div className='row'>
              <div className='col-lg-8'>
                <div className='post-detail__wrapper'>
                  <div className='post-detail__heading'>
                    <h1 className='title'>{postData.title}</h1>
                    <div className='meta'>{postData.formatted_added_time}</div>
                  </div>
                  <article className='post-detail__content'>
                    <div className='post-detail__main-image'>
                      <img src={postData.image_1} alt={postData.title}/>
                    </div>
                    <p>{postData.content_1}</p>
                    {
                      postData.image_2 && <img src={postData.image_2} alt={postData}/> 
                    }
                    {
                      postData.content_2 && <p>{postData.content_2}</p>
                    }
                    {
                      postData.image_3 && <img src={postData.image_3} alt={postData}/> 
                    }
                    {
                      postData.content_3 && <p>{postData.content_3}</p>
                    }
                  </article>
                </div>
              </div>
              <div className='col-lg-4'></div>
            </div>
          </div>
          <Footer/>
        </div>
      </main>
    </>
  )
}

export default PostDetail