import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Head from "next/head";
import PostItem from '../components/PostItem';
import Breadcrumbs from '../components/BreadCrumbs';



function AllCategories() {
    const router = useRouter()

    const [categoryData, setCategoryData] = useState(null);
    useEffect(() => {
        async function fetchData() {
        const response = await fetch(`http://127.0.0.1:8000/api/v1/category`);
        const data = await response.json();
        setCategoryData(data);
        }
        fetchData();
    }, []);

  if (!categoryData) {
    return <div>Loading...</div>;
  }

  const crumbs = [
    { name: 'главная', path: '/' },
    { name: 'категории', path: null },
  ];
  
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='category-detail'>
            <Header/>
            <div className='category-detail__content mt-5 mb-5'>
                <div className='container'>
                    <div className='category-detail__heading'>
                        <h1 className='category-detail__title '>{categoryData.title}</h1>
                        <Breadcrumbs crumbs={crumbs}/>
                    </div>
                </div>
            </div>
            <div className='tag-detail__posts mb-5'>
                <div className='container'>
                    <div className='row'>
                        {
                            categoryData.category_posts && categoryData.category_posts.map((item) => (
                                <PostItem 
                                key={item.id}
                                id={item.id}
                                class='col-sm-4'
                                date={item.formatted_added_time}
                                content_1={item.content_1}
                                image_1={item.image_1}
                                content_2={item.content_2}
                                image_2={item.image_2}
                                content_3={item.content_3}
                                image_3={item.image_3}
                                slug={item.slug}
                                category={item.category[0].title}
                                title={item.title}
                                tags={item.tags}
                              />
                            ))
                        }
                    </div>
                </div>
            </div>
            <Footer/>
        </div>
      </main>
    </>
    
  )
}

export default AllCategories