import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { useRouter } from "next/router";
import Homepage from "./Homepage";


export default function Home() {
  const [isBrowser, setIsBrowser] = useState(false);

  useEffect(() => {
  setIsBrowser(typeof window !== "undefined");
  }, []);

  const router = useRouter();

  return isBrowser ? (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <Homepage />
      </main>
      <Footer/>
    </>
  ) : null
}
