import React, { useState, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Homepage from "./components/Homepage";


export default function Home() {
  const [isBrowser, setIsBrowser] = useState(false);

  useEffect(() => {
  setIsBrowser(typeof window !== "undefined");
  }, []);


  return isBrowser ? (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <Homepage />
      </main>
      <Footer/>
    </>
  ) : null
}
